package org.endeavourhealth.informationmanager.common.transform.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.endeavourhealth.informationmanager.common.models.ConceptStatus;

import java.util.ArrayList;
import java.util.List;

@JsonPropertyOrder({"id","status","version","iri","name","description",
        "code","scheme","annotations"})
public class Concept implements IMAnnotated{
    private String iri;
    private String name;
    private String description;
    private String code;
    private String scheme;
    private String id;
    private ConceptStatus status;
    private Integer version;
    private List<Concept> isA;
    private List<Annotation> annotations;
    private boolean isRef;


    @Override
    public ConceptStatus getStatus() {
        return status;
    }

    @Override
    public Concept setStatus(ConceptStatus status) {
        this.status=status;
        return this;
    }

    @Override
    public Integer getVersion() {
        return version;
    }

    @Override
    public Concept setVersion(Integer version) {
        this.version= version;
        return this;
    }

    @Override
    public Concept setId(String id) {
        this.id= id;
        return this;
    }

    @Override
    public String getId() {
        return id;
    }


    public Concept() {}

    public Concept(String iri, String name) {
        this.iri = iri;
        this.name = name;
    }

    public String getIri() {
        return iri;
    }

    public Concept setIri(String iri) {
        this.iri = iri;
        return this;
    }



    public String getName() {
        return name;
    }

    public Concept setName(String name) {
        this.name = name;
        return this;
    }

    public String getDescription() {
        return description;
    }

    public Concept setDescription(String description) {
        this.description = description;
        return this;
    }

    public String getScheme() {
        return scheme;
    }

    public Concept setScheme(String scheme) {
        this.scheme = scheme;
        return this;
    }

    public String getCode() {
        return code;
    }

    public Concept setCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Returns a list of IRIs which are the direct superconcepts of this concept
     * <p>This may include asserted superclasses and super properties and equivalent classes as well as those generated by a reasoner</p>
     * @return list of super concepts
     */
    @JsonProperty("IsA")
    public List<Concept> getIsA() {
        return isA;
    }

    public Concept setIsA(List<Concept> isA) {
        this.isA = isA;
        return this;
    }
    public Concept addIsa(Concept isa){
        if (this.isA==null)
            isA= new ArrayList<>();
        isA.add(isa);
        return this;
    }

    @JsonProperty("Annotation")
    public List<Annotation> getAnnotations() {
        return annotations;
    }

    public Concept setAnnotations(List<Annotation> annotations) {
        this.annotations = annotations;
        return this;
    }
    public Concept addAnnotation(Annotation annotation) {
        if (this.annotations==null)
            this.annotations= new ArrayList<>();
        this.annotations.add(annotation);
        return this;
    }

    @JsonProperty("isRef")
    public boolean getisRef() {
        return isRef;
    }

    public Concept setIsRef(boolean ref) {
        isRef = ref;
        return this;
    }
}
