package org.endeavourhealth.informationmanager.common.transform;


import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.misc.IntervalSet;


import java.util.ArrayList;
import java.util.List;

public class IMLangErrorListener extends BaseErrorListener {

   private List<IMSyntaxError> errors= new ArrayList<>();



   /**
    * Override of antlr error listener to capture errors, position and expected tokens
    * @param recognizer  the recogniser being either the lexer or the parser
    * @param offendingSymbol the symbol that has caused the error
    * @param line the line number on which the error occurs
    * @param charPositionInLine  the position in the line in which the error occurs
    * @param msg  the textual error message generated by antlr parser
    * @param e the recognition exception generated by the antlr parser
    */
   @Override
   public void syntaxError(Recognizer<?, ?> recognizer,
                           Object offendingSymbol,
                           int line,
                           int charPositionInLine,
                           String msg,
                           RecognitionException e) {
      IMSyntaxError error = new IMSyntaxError();
      errors.add(error);
      error.setMsg(msg);
      error.setLine(line);
      error.setCharPositionInLine(charPositionInLine);

      if (offendingSymbol instanceof org.antlr.v4.runtime.CommonToken)
         error.setBadToken((CommonToken) offendingSymbol);
      if (recognizer instanceof Lexer) {
         Lexer lexer= (Lexer) recognizer;
         error.setLexer(lexer);
      } else {
         Parser parser = (Parser) recognizer;
         error.setParser(parser);
         ParserRuleContext ctx = parser.getContext();
         error.setExpectedTokens(parser.getExpectedTokens());
      }

   }


   /**
    * gets the error object created and populated by this error listener
    * @return the error object for use in application UI.
    */
   public List<IMSyntaxError> getErrors() {
      return errors;
   }


}

