DROP TABLE IF EXISTS document;
CREATE TABLE document
(
    dbid    INT AUTO_INCREMENT COMMENT 'Unique DBID generated by hashing the iri',
    path    VARCHAR(255) NOT NULL COMMENT 'Relative path of document',
    version VARCHAR(10)  NOT NULL COMMENT 'Current document version',
    draft   BOOLEAN      NOT NULL DEFAULT TRUE COMMENT 'Document draft status',

    PRIMARY KEY document_pk (dbid)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS document_archive;
CREATE TABLE document_archive
(
    dbid    INT         NOT NULL COMMENT 'Document DBID',
    version VARCHAR(10) NOT NULL COMMENT 'Document version number',
    data    LONGBLOB    NOT NULL COMMENT 'Document contents (compressed JSON)',

    PRIMARY KEY document_archive_pk (dbid, version),
    INDEX document_dbid_idx (dbid)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS concept;
CREATE TABLE concept
(
    dbid        INT AUTO_INCREMENT,
    document    INT      NOT NULL COMMENT '',
    id          VARCHAR(140) COLLATE utf8_bin COMMENT 'Unique IM concept identifier (case sensitive)',
    name        VARCHAR(255) COMMENT '',
    short_name  VARCHAR(60) COMMENT '',
    description VARCHAR(400) COMMENT '',
    scheme      INT COMMENT '',
    code        VARCHAR(20) COLLATE utf8_bin COMMENT '',
    -- Meta
    status      TINYINT  NOT NULL DEFAULT 0 COMMENT 'Status - 0 = Draft, 1 = Incomplete, 2 = Active, 3 = Deprecated',
    updated     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    revision    INT      NOT NULL DEFAULT 1,
    published   VARCHAR(10) COMMENT 'Last published version',

    PRIMARY KEY concept_dbid_pk (dbid),
    UNIQUE KEY concept_id_uq (id),
    UNIQUE KEY concept_code_scheme (code, scheme),
    INDEX concept_updated_idx (updated),
    INDEX concept_document_status (document, status),
    FULLTEXT concept_name_ftx (name)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS concept_property_object;
CREATE TABLE concept_property_object
(
    dbid     INT NOT NULL COMMENT 'Concept DBID',
    `group`  INT NOT NULL DEFAULT 0 COMMENT 'Property group id',
    property INT NOT NULL COMMENT 'Property concept dbid',
    value    INT NOT NULL COMMENT 'Property value concept dbid',

    INDEX concept_property_object_idx (dbid),
    INDEX concept_property_object_property_value (property, value),
    INDEX concept_property_object_value_idx (value)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS concept_property_data;
CREATE TABLE concept_property_data
(
    dbid     INT NOT NULL COMMENT 'Concept DBID',
    `group`  INT NOT NULL DEFAULT 0 COMMENT 'Property group id',
    property INT NOT NULL COMMENT 'Property concept dbid',
    value    VARCHAR(400) NOT NULL COLLATE utf8_bin COMMENT 'Property value data (case sensitive)',

    INDEX concept_property_data_idx (dbid),
    INDEX concept_property_data_property_value (property, value)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS concept_class;
CREATE TABLE concept_class
(
    dbid    INT NOT NULL COMMENT 'Concept DBID',
    class   INT NOT NULL COMMENT 'Class DBID',

    INDEX concept_class_concept (dbid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS concept_domain;
CREATE TABLE concept_domain
(
    dbid        INT NOT NULL COMMENT 'Concept DBID',
    property    INT NOT NULL COMMENT 'Property DBID',
    mandatory   BOOLEAN NOT NULL,
    `limit`     INT NOT NULL COMMENT '0 = Unlimited',

    INDEX concept_domain_concept (dbid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS concept_range;
CREATE TABLE concept_range
(
    dbid    INT NOT NULL COMMENT 'Concept DBID',
    `range` TEXT NOT NULL COMMENT 'Range expression',

    PRIMARY KEY concept_range_pk (dbid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS concept_term_map;
CREATE TABLE concept_term_map
(
    term      VARCHAR(250) NOT NULL,
    type      INT          NOT NULL,
    target    INT          NOT NULL,
    draft     BOOLEAN      NOT NULL DEFAULT TRUE,
    published VARCHAR(10),
    updated   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY concept_term_map_pk (term, type),
    INDEX concept_term_map_draft (draft)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS im_instance;
CREATE TABLE im_instance
(
    dbid INT AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    url  VARCHAR(400) NOT NULL,

    PRIMARY KEY im_instance_pk (dbid)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

-- RESERVED "term maps" document (dbid 0)
SET SESSION sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

INSERT INTO document (dbid, path, version)
VALUES (0, 'InformationModel/dm/TermMaps', '1.0.0');

-- Workflow manager tables
DROP TABLE IF EXISTS workflow_task;
CREATE TABLE workflow_task
(
    dbid      INTEGER AUTO_INCREMENT,
    category  TINYINT  NOT NULL COMMENT '0=Concept mapping, 1=Term mapping',
    user_id   CHAR(36) BINARY COMMENT 'The id of the last user to modify this task',
    user_name VARCHAR(50) COMMENT 'Their (display) name',
    subject   VARCHAR(100) COMMENT 'The task subject/name/title',
    status    TINYINT  NOT NULL DEFAULT 0 COMMENT 'Task status - 0=New, 1=In progress, 2=Complete, 3=Archived',
    data      JSON COMMENT 'The task data',
    created   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY workflow_task_pk (dbid),
    INDEX workflow_task_category (category)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS workflow_task_category;
CREATE TABLE workflow_task_category
(
    dbid TINYINT     NOT NULL,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY workflow_task_category_pk (dbid)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
