DROP TABLE IF EXISTS document;
CREATE TABLE document (
    dbid INT AUTO_INCREMENT                 COMMENT 'Unique DBID generated by hashing the iri',
    path VARCHAR(255) NOT NULL              COMMENT 'Relative path of document',
    version VARCHAR(10) NOT NULL            COMMENT 'Current document version',
    draft BOOLEAN NOT NULL DEFAULT TRUE     COMMENT 'Document draft status',

    PRIMARY KEY document_pk (dbid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS document_archive;
CREATE TABLE document_archive (
    dbid INT NOT NULL                       COMMENT 'Document DBID',
    version VARCHAR(10) NOT NULL            COMMENT 'Document version number',
    data LONGBLOB  NOT NULL                 COMMENT 'Document contents (compressed JSON)',

    PRIMARY KEY document_archive_pk (dbid, version),
    INDEX document_dbid_idx (dbid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS concept;
CREATE TABLE concept (
    dbid INT AUTO_INCREMENT,
    document INT NOT NULL,
    data JSON NOT NULL,
    status TINYINT NOT NULL DEFAULT 0 COMMENT 'Status - 0 = Draft, 1 = Incomplete, 2 = Active, 3 = Deprecated',
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    revision INT NOT NULL DEFAULT 1,
    published VARCHAR(10)             COMMENT 'Last published version',

    id VARCHAR(140) COLLATE utf8_bin  GENERATED ALWAYS AS (`data` ->> '$.id') STORED NOT NULL,
    name VARCHAR(255)                 GENERATED ALWAYS AS (`data` ->> '$.name') STORED,
    short_name VARCHAR(60)            GENERATED ALWAYS AS (`data` ->> '$.short_name') VIRTUAL,
    description VARCHAR(400)          GENERATED ALWAYS AS (`data` ->> '$.description') VIRTUAL,
    scheme VARCHAR(50)                GENERATED ALWAYS AS (`data` ->> '$.code_scheme.id') STORED,
    code VARCHAR(20) COLLATE utf8_bin GENERATED ALWAYS AS (`data` ->> '$.code') STORED,

    PRIMARY KEY concept_dbid_pk (dbid),
    UNIQUE KEY concept_id_uq (id),
    UNIQUE KEY concept_code_scheme (code, scheme),
    INDEX concept_updated_idx (updated),
    INDEX concept_document_status (document, status),
    FULLTEXT concept_name_ftx (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS concept_term_map;
CREATE TABLE concept_term_map (
    term VARCHAR(250) COLLATE utf8_bin NOT NULL,
    type INT NOT NULL,
    target INT NOT NULL,
    draft BOOLEAN NOT NULL DEFAULT TRUE,
    published VARCHAR(10),
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY concept_term_map_pk (term, type),
    INDEX concept_term_map_draft (draft)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS im_instance;
CREATE TABLE im_instance (
    dbid INT AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    url VARCHAR(400) NOT NULL,

    PRIMARY KEY im_instance_pk (dbid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- RESERVED "term maps" document (dbid 0)
SET SESSION sql_mode='NO_AUTO_VALUE_ON_ZERO';

INSERT INTO document (dbid, path, version)
VALUES (0, 'InformationModel/dm/TermMaps', '1.0.0');

-- Workflow manager tables
DROP TABLE IF EXISTS workflow_task;
CREATE TABLE workflow_task (
    dbid INTEGER AUTO_INCREMENT,
    category TINYINT NOT NULL           COMMENT '0=Concept mapping, 1=Term mapping',
    user_id CHAR(16) BINARY              COMMENT 'The id of the last user to modify this task',
    user_name VARCHAR(50)                COMMENT 'Their (display) name',
    subject VARCHAR(100)                COMMENT 'The task subject/name/title',
    status TINYINT NOT NULL DEFAULT 0   COMMENT 'Task status - 0=New, 1=In progress, 2=Complete, 3=Archived',
    data JSON                           COMMENT 'The task data',
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY workflow_task_pk (dbid),
    INDEX workflow_task_category(category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS workflow_task_category;
CREATE TABLE workflow_task_category (
    dbid TINYINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY workflow_task_category_pk (dbid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
