-- MySQL Script generated by MySQL Workbench
-- Mon Jul  3 16:55:47 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema information_model
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema information_model
-- -----------------------------------------------------
drop schema if exists information_model;

CREATE SCHEMA IF NOT EXISTS `information_model` DEFAULT CHARACTER SET utf8 ;
USE `information_model` ;

-- -----------------------------------------------------
-- Table `information_model`.`concept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_model`.`concept` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(250) NULL DEFAULT NULL,
  `status` TINYINT NULL,
  `class` BIGINT NULL DEFAULT NULL,
  `short_name` VARCHAR(125) NULL DEFAULT NULL,
  `description` VARCHAR(10000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_model`.`concept_relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_model`.`concept_relationship` (
  `id` BIGINT NOT NULL COMMENT 'Relationship Id',
  `source_concept` BIGINT NOT NULL COMMENT 'The Source concept in concept table',
  `relationship_type` BIGINT NULL DEFAULT NULL COMMENT 'Concept identifier of the relationship e.g “has subtype”',
  `target_concept` BIGINT NOT NULL COMMENT 'The Target concept in concept table',
  `target_label` VARCHAR(125) NULL DEFAULT NULL COMMENT 'An abbreviated version of the target concept name (may be the same as the short name or even shorter)',
  `relationship_order` INT(4) NULL DEFAULT NULL COMMENT 'In the context of the expression, the order in which the relationships are presented',
  PRIMARY KEY (`id`),
  INDEX `concept_fk_idx` (`source_concept` ASC, `target_concept` ASC),
  INDEX `target_concept_fk` (`target_concept` ASC),
  INDEX `relationship_fk_idx` (`relationship_type` ASC),
  CONSTRAINT `relationship_fk`
    FOREIGN KEY (`relationship_type`)
    REFERENCES `information_model`.`concept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `source_concept_fk`
    FOREIGN KEY (`source_concept`)
    REFERENCES `information_model`.`concept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `target_concept_fk`
    FOREIGN KEY (`target_concept`)
    REFERENCES `information_model`.`concept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_model`.`field_actual_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_model`.`field_actual_value` (
  `id` BIGINT NOT NULL,
  `field` BIGINT NULL,
  `value` BIGINT NULL,
  `weighting` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `field_actual_value_field_idx` (`field` ASC),
  INDEX `field_actual_value_concept_idx` (`value` ASC),
  CONSTRAINT `field_actual_value_field`
    FOREIGN KEY (`field`)
    REFERENCES `information_model`.`concept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `field_actual_value_concept`
    FOREIGN KEY (`value`)
    REFERENCES `information_model`.`concept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `information_model`.`concept_actual_range`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_model`.`concept_actual_range` (
  `id` BIGINT NOT NULL,
  `field` BIGINT NOT NULL,
  `range qualifier` BIGINT NULL,
  `lower_limit` FLOAT NULL,
  `range operator` VARCHAR(2) NULL,
  `upper_limit` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `field_actual_range_field_idx` (`field` ASC),
  INDEX `field_actual_range_qualifier_idx` (`range qualifier` ASC),
  CONSTRAINT `field_actual_range_field`
    FOREIGN KEY (`field`)
    REFERENCES `information_model`.`concept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `field_actual_range_qualifier`
    FOREIGN KEY (`range qualifier`)
    REFERENCES `information_model`.`concept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `information_model`.`concept_expression`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_model`.`concept_expression` (
  `id` BIGINT NOT NULL,
  `concept` BIGINT NULL,
  `attribute` BIGINT NULL,
  `value_concept` BIGINT NULL,
  `order` INT(4) NULL,
  PRIMARY KEY (`id`),
  INDEX `concept_idx` (`concept` ASC),
  INDEX `attribute_idx` (`attribute` ASC),
  INDEX `value_concept_idx` (`value_concept` ASC),
  CONSTRAINT `concept`
    FOREIGN KEY (`concept`)
    REFERENCES `information_model`.`concept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `attribute`
    FOREIGN KEY (`attribute`)
    REFERENCES `information_model`.`concept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `value_concept`
    FOREIGN KEY (`value_concept`)
    REFERENCES `information_model`.`concept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `information_model`.`concept_range`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_model`.`concept_range` (
  `id` BIGINT NOT NULL,
  `concept` BIGINT NULL,
  `range_qualifier` BIGINT NULL,
  `operator` VARCHAR(2) NULL,
  `lower_limit` FLOAT NULL,
  `upper_limit` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `attribute_range_concept_idx` (`concept` ASC),
  INDEX `attribute_range_qualifier_idx` (`range_qualifier` ASC),
  CONSTRAINT `attribute_range_concept`
    FOREIGN KEY (`concept`)
    REFERENCES `information_model`.`concept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `attribute_range_qualifier`
    FOREIGN KEY (`range_qualifier`)
    REFERENCES `information_model`.`concept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `information_model`.`concept_code_scheme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_model`.`concept_code_scheme` (
  `id` INT NOT NULL,
  `concept` BIGINT NULL,
  `code` VARCHAR(20) NULL,
  `scheme` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `code_scheme_concept_idx` (`concept` ASC),
  CONSTRAINT `code_scheme_concept`
    FOREIGN KEY (`concept`)
    REFERENCES `information_model`.`concept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
